apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobber-app
  template:
    metadata:
      labels:
        app: jobber-app
        type: backend
    spec:
      containers:
      - name: jobber-ctner
        image: monix193/jobber:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
    