apiVersion: apps/v1
kind: Deployment
metadata:
  name: Jobber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Jobber
  template:
    metadata:
      labels:
        app: Jobber
    spec:
      containers:
      - name: Jobber
        image: monix193/jobber:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
    