kind: Service
apiVersion: v1
metadata:
  name:  jobber-service
spec:
    type:  NodePort
    ports:
    - name:  name-of-the-port
      port:  80
      targetPort:  8080
      nodePort: 30008
    selectors:
      app: jobber-app
      type: backend